name: Trigger auto deployment for tacto-api

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/tacto-api-AutoDeployTrigger-98bb5b5b-f7ee-4231-9352-55f352b3c994.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.TACTOAPI_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.TACTOAPI_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.TACTOAPI_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: docker.io
          registryUsername: ${{ secrets.TACTOAPI_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.TACTOAPI_REGISTRY_PASSWORD }}
          containerAppName: tacto-api
          resourceGroup: fastapi_apps_experiments
          imageToBuild: arthurzakirov/tacto-api:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


